name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow write access to checkout and commit to gh-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '18' # Specify your desired Node.js version
          cache: 'npm' # Add caching for npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build # This script should generate files in 'dist'

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll # Add .nojekyll file to disable Jekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Sticking with v3 as it's stable, v4 is also an option
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]' # Explicitly set commit user
          user_email: 'github-actions[bot]@users.noreply.github.com' # Explicitly set commit email
          commit_message: 'Deploy to GitHub Pages (via GitHub Actions)' # Optional: Custom commit message
          # keep_files: false # Optional: Set to true to keep existing files on gh-pages branch
          # cname: example.com # Optional: if using a custom domain
